const AlumniData = [
  {
    "name": "Dhruthi L",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained teamwork skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.8
  },
  {
    "name": "Harsha Vardhan S D",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.4
  },
  {
    "name": "Chinmaya M A",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "EcoLabs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Enhanced problem-solving through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.5
  },
  {
    "name": "Anusha M G",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.2
  },
  {
    "name": "Monika B",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " NTT Data",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.7
  },
  {
    "name": "Keshav Regmi",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved communication during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.9
  },
  {
    "name": "Aastha Singh",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "ValTech India",
    "image": "https://via.placeholder.com/80?text=MS",
    "college": "ABC College",
    "degree": "BE",
    "experience": "Mastered debugging in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/mohammedafan/",
    "package": 10.3
  },
  {
    "name": "Abhishek Singh Chauhan",
    "role": "Designation",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed analytical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.1
  },
  {
    "name": "Dhiraj Mandal",
    "role": "Designation",
    "location": "Surat",
    "rating": 5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry exposure through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 13.6
  },
  {
    "name": "Adarsh Gidd",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Mpowered Health",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed software tools in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.8
  },
  {
    "name": "Deepak Kumar",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned agile methods in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.9
  },
  {
    "name": "Harshitha",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": "BYJUs  India Pvt Ltd",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved coding proficiency via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 14.2
  },
  {
    "name": "Jeevan S J",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Enhanced teamwork in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.4
  },
  {
    "name": "Ankitha R",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built project experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.3
  },
  {
    "name": "Gagana Y R",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Mastered time management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.8
  },
  {
    "name": "Chandana N",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed leadership skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 10.7
  },
  {
    "name": "Jeevan S Jayaramegowda",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained practical experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.8
  },
  {
    "name": "Kruthik B",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 13.1
  },
  {
    "name": "Monika Muniraju",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.5
  },
  {
    "name": "Arvind Kumar G",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed programming skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.6
  },
  {
    "name": "Kumar Vedant",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": "TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built industry knowledge in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 14.0
  },
  {
    "name": "Gagan C",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.9
  },
  {
    "name": "Aishwarya",
    "role": "Frontend Developer",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained frontend experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.4
  },
  {
    "name": "Anirudh B Mitta",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned software development in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.1
  },
  {
    "name": "Keerthana S C",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved teamwork skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 10.0
  },
  {
    "name": "Apurv",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.6
  },
  {
    "name": "Bhargav Urs S",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Torry Harris",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project experience via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.5
  },
  {
    "name": "Beluvigi Sreeranga",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.0
  },
  {
    "name": "Govind Biradar",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned agile practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.7
  },
  {
    "name": "Ayush Kumar Mishra",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " Hashedin Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 13.3
  },
  {
    "name": "Lavanya YN",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.2
  },
  {
    "name": "Issat Riyaz",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved problem-solving in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.4
  },
  {
    "name": "Mansi Srinivas",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.2
  },
  {
    "name": "Bhuvaneshwari R",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed coding skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.4
  },
  {
    "name": "Kartik Dandooti",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry insights in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.0
  },
  {
    "name": "Aruna K",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned project skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.6
  },
  {
    "name": "Maheshwari Khelge",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.8
  },
  {
    "name": "Anusha Makam Gopalakrishna",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained coding experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.7
  },
  {
    "name": "Bhavana Hs",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed professional skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 13.8
  },
  {
    "name": "Ashwas Ajay",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.6
  },
  {
    "name": "Dhruvin Kanani",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Maple Labs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.2
  },
  {
    "name": "CHANDRIKA S N",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned industry practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.7
  },
  {
    "name": "LAXMAN KUDDEMMI",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.3
  },
  {
    "name": "Tejas M N",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.5
  },
  {
    "name": "Abhijit Nashi",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Torry Harris",
    "image": "https://via.placeholder.com/80?text=SB",
    "college": "Saptagiri College of Engineering",
    "degree": "BE",
    "experience": "Honed software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.9
  },
  {
    "name": "Kavya R",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.1
  },
  {
    "name": "Dinesh N",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4,
    "pre": "Fresher",
    "post": " TCS",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.5
  },
  {
    "name": "Adnan Haider",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.4
  },
  {
    "name": "MOHAMMAD ROOH ULLAH",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.6
  },
  {
    "name": "Gagana C M",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.9
  },
  {
    "name": "Deepak Somayya Gond",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": " 6D Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.5
  },
  {
    "name": "Ayshna Goenka",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned coding techniques in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.3
  },
  {
    "name": "Anusha Akula",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained professional experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.8
  },
  {
    "name": "Suhas Indgiri",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.8
  },
  {
    "name": "INCHARA KARANTH",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.2
  },
  {
    "name": "AJAY H Hegde",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 9.7
  },
  {
    "name": "Chiranjeevi B Shankara",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.9
  },
  {
    "name": "Harshitha K M",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.6
  },
  {
    "name": "Kanneboyina Likith Adithya ",
    "role": "UI/UX DESIGNER",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "EXL",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Lovely professional University ",
    "degree": "B.Tech",
    "experience": "Developed UI/UX design skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.7
  },
  {
    "name": "Gande Tejaswini  ",
    "role": "SDA",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": "Mortgage Loans",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Vaagdevi college of engineering  ",
    "degree": "B.Tech",
    "experience": "Gained software development expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.0
  },
  {
    "name": "Suba Dharshini P",
    "role": "SDA",
    "location": "Pune",
    "rating": 3,
    "pre": "Fresher",
    "post": "Mortgage Loans",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Mahendra engineering college   ",
    "degree": "MCA",
    "experience": "Enhanced coding proficiency through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 5.5
  },
  {
    "name": "GILAKA SIVA PEDDANNA ",
    "role": "Management Trainee",
    "location": "Kolkata",
    "rating": 3,
    "pre": "Fresher",
    "post": "Saffron Sweets",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "KL UNIVERSITY ",
    "degree": "MBA",
    "experience": "Acquired management skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 5.8
  },
  {
    "name": "K.J.Pavani Durga",
    "role": "Business Developement Associate",
    "location": "Chennai",
    "rating": 3,
    "pre": "Fresher",
    "post": "Rocklight",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Sri Padmavati Mahila Viswa Vidyalayam ",
    "degree": "M.Com",
    "experience": "Honed business development skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.0
  },
  {
    "name": "ANUSHA R",
    "role": "BACKEND SUPPORT",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": "Phoenix business Advisory",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "SRM INSTITUTE OF SCIENCE AND TECHNOLOGY  ",
    "degree": "Master of public health ",
    "experience": "Strengthened backend support skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.3
  },
  {
    "name": "Saanchitha D",
    "role": "AM - FP&A ",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": "Genpact",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Dayananda Sagar University",
    "degree": "Computer Science and Engineering ",
    "experience": "Improved budgeting and forecasting skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.1
  },
  {
    "name": "Gokulakannan K ",
    "role": "Process Associate",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "Hrim Innovation",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Kalasalingam Academy of Research and Education ",
    "degree": "B.Tech CSE",
    "experience": "Gained process optimization skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.6
  },
  {
    "name": "Anusha G",
    "role": "Sr Executive- Accounts",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Genpact",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Annamacharya institute of technology and science ",
    "degree": "ECE",
    "experience": "Enhanced accounting skills through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.0
  },
  {
    "name": "Rishabh Nagar",
    "role": "Process Associate ",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Brillo",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Chandigarh University  ",
    "degree": "Be- cse",
    "experience": "Developed process management skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 11.3
  },
  {
    "name": "Jayita Ghorai ",
    "role": "Full stack developer",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capegemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "College of Engineering and Management, Kolaghat ",
    "degree": "Bachelor of Technology ",
    "experience": "Mastered full stack development during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.0
  },
  {
    "name": "Bhavin Sali ",
    "role": "AM - FP&A ",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "SRM University",
    "degree": " MCA ",
    "experience": "Built financial planning skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 8.5
  },
  {
    "name": "HRUSHIKESH S ",
    "role": "Ui/UX DESIGNER",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Eco Lbs ",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "SJCIT ",
    "degree": "CSE",
    "experience": "Refined user interface design skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 13.0
  },
  {
    "name": "Kartik chauhan ",
    "role": "Technical bug checker",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "6d technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "JC Bose University of science and technology ",
    "degree": "B.tech(computer engineering)",
    "experience": "Sharpened debugging skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 7.4
  },
  {
    "name": "K J Pavani Durga ",
    "role": "Management Trainee",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Brillo",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Sri Padmavati Mahila Viswa Vidhayalayam ",
    "degree": "Finance ",
    "experience": "Cultivated leadership skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 6.8
  },
  {
    "name": "Pushpanjali verma ",
    "role": "Ui/UX DESIGNER",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Accenture ASW",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Kalinga institute of industrial technology ",
    "degree": "B.tech",
    "experience": "Advanced user experience design skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/",
    "package": 12.3
  }
];

export default AlumniData;