
const AlumniData =
[
  {
    "name": "Dhruthi L",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained teamwork skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Harsha Vardhan S D",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Chinmaya M A",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "EcoLabs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Enhanced problem-solving through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Anusha M G",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Monika B",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " NTT Data",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Keshav Regmi",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved communication during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Aastha Singh",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "ValTech India",
    "image": "https://via.placeholder.com/80?text=MS",
    "college": "ABC College",
    "degree": "BE",
    "experience": "Mastered debugging in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/mohammedafan/"
  },
  {
    "name": "Abhishek Singh Chauhan",
    "role": "Designation",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed analytical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Dhiraj Mandal",
    "role": "Designation",
    "location": "Surat",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry exposure through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Adarsh Gidd",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Mpowered Health",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed software tools in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Deepak Kumar",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned agile methods in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Harshitha",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": "BYJUs  India Pvt Ltd",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved coding proficiency via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Jeevan S J",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Enhanced teamwork in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Ankitha R",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built project experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Gagana Y R",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Mastered time management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Chandana N",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed leadership skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Jeevan S Jayaramegowda",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained practical experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Kruthik B",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Monika Muniraju",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Arvind Kumar G",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed programming skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Kumar Vedant",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": "Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built industry knowledge in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Gagan C",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Aishwarya",
    "role": "Frontend Developer",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained frontend experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Anirudh B Mitta",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned software development in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Keerthana S C",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved teamwork skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Apurv",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Bhargav Urs S",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Torry Harris",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project experience via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Beluvigi Sreeranga",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Govind Biradar",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned agile practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Ayush Kumar Mishra",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " Hashedin Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Lavanya YN",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Issat Riyaz",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Improved problem-solving in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Mansi Srinivas",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Bhuvaneshwari R",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed coding skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Kartik Dandooti",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry insights in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Aruna K",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned project skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Maheshwari Khelge",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Anusha Makam Gopalakrishna",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained coding experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Bhavana Hs",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed professional skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Ashwas Ajay",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Dhruvin Kanani",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Maple Labs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "CHANDRIKA S N",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned industry practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "LAXMAN KUDDEMMI",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Tejas M N",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Abhijit Nashi",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Torry Harris",
    "image": "https://via.placeholder.com/80?text=SB",
    "college": "Saptagiri College of Engineering",
    "degree": "BE",
    "experience": "Honed software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Kavya R",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Dinesh N",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Adnan Haider",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "MOHAMMAD ROOH ULLAH",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Gagana C M",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained industry experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Deepak Somayya Gond",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": " 6D Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Ayshna Goenka",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned coding techniques in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Anusha Akula",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained professional experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Suhas Indgiri",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "INCHARA KARANTH",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Honed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "AJAY H Hegde",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Gained project skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Chiranjeevi B Shankara",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Built technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  },
  {
    "name": "Harshitha K M",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "experience": "Learned software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/aastha-singh-123456789/"
  }
];
  
  export default AlumniData;
  