const AlumniData = [
  {
    "name": "Dhruthi L",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Gained teamwork skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Harsha Vardhan S D",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Chinmaya M A",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "EcoLabs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Enhanced problem-solving through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Anusha M G",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Learned project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Monika B",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " NTT Data",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Built technical skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Keshav Regmi",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Improved communication during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Aastha Singh",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "ValTech India",
    "image": "https://via.placeholder.com/80?text=MS",
    "college": "ABC College",
    "degree": "BE",
    "package": "13 LPA",
    "experience": "Mastered debugging in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Abhishek Singh Chauhan",
    "role": "Designation",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "Honed analytical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Dhiraj Mandal",
    "role": "Designation",
    "location": "Surat",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "17 LPA",
    "experience": "Gained industry exposure through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Adarsh Gidd",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Mpowered Health",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Developed software tools in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Deepak Kumar",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Learned agile methods in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Harshitha",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": "BYJUs  India Pvt Ltd",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Improved coding proficiency via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Jeevan S J",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Enhanced teamwork in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Ankitha R",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Built project experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Gagana Y R",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Mastered time management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Chandana N",
    "role": "Designation",
    "location": "Puen",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience": "Developed leadership skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Jeevan S Jayaramegowda",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "Gained practical experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Kruthik B",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "17 LPA",
    "experience": "Improved technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Monika Muniraju",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Learned collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Arvind Kumar G",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Honed programming skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Kumar Vedant",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 5,
    "pre": "Fresher",
    "post": "Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Built industry knowledge in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Gagan C",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Developed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Aishwarya",
    "role": "Frontend Developer",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Gained frontend experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Anirudh B Mitta",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post": "Brillio",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Learned software development in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Keerthana S C",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience": "Improved teamwork skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Apurv",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "Developed coding skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Bhargav Urs S",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Torry Harris",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "17 LPA",
    "experience": "Gained project experience via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Beluvigi Sreeranga",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Honed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Govind Biradar",
    "role": "Designation",
    "location": "Surat",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Learned agile practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Ayush Kumar Mishra",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " Hashedin Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Built coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Lavanya YN",
    "role": "Designation",
    "location": "Hyderabad",
    "rating": 4.5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Gained leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Issat Riyaz",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Improved problem-solving in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Mansi Srinivas",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Bhuvaneshwari R",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience": "Honed coding skills via internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "极linkdinUrl": ""
  },
  {
    "name": "Kartik Dandooti",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "极pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "Gained industry insights in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Aruna K",
    "role": "Designation",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "极XYZ Institute",
    "degree": "B.Tech",
    "package": "17 LPA",
    "experience": "Learned project skills in internship",
    "pre极Role": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Maheshwari Khelge",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Built technical expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Anusha Makam Gopalakrishna",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "Accenture - ASE",
    "极image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Gained coding experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Bhavana Hs",
    "role": "Designation",
    "location": "Del极hi",
    "rating": 5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "极https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Developed professional skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Ashwas Ajay",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Honed problem-solving skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Dhruvin Kanani",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Maple Labs",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Gained technical skills in internship",
    "preRole": "Internship from极 Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "CHANDRIKA S N",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Learned industry practices in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "LAXMAN KUDDEMMI",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/极80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience": "Developed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Tejas M N",
    "role": "Designation",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "极Gained project management in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Abhijit Nashi",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Torry Harris",
    "image": "https://via.placeholder.com/80?text=SB",
    "college": "Saptagiri College of Engineering",
    "degree": "BE",
    "package": "17 LPA",
    "experience": "Honed software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Kavya R",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Built collaboration skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Dinesh N",
    "role": "Designation",
   "location": "Chennai",
    "rating": 4,
    "pre": "极Fresher",
    "post": " Tata Consultancy Services",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Gained coding proficiency in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Adnan Haider",
    "role": "Designation",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Developed technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdin极Url": ""
  },
  {
    "name": "MOHAMMAD ROOH ULLAH",
    "role": "Designation",
    "location": "Pune",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Honed leadership skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Gagana C M",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "8 LPA",
    "experience": "Gained industry experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Deepak Somayya Gond",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": " 6D Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Built software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Ayshna Goenka",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "极college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience": "Learned coding techniques in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Anusha Akula",
    "role": "Designation",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "Codecraft Technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "10 LPA",
    "experience": "Gained professional experience in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Suhas Indgiri",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "17 LPA",
    "experience": "Developed teamwork skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "INCHARA KARANTH",
    "role": "Designation",
    "location": "Pune",
    "rating": 5,
    "pre": "Fresher",
    "post极": "Cognizant GenC",
    "image": "https://via.placeholder.com/80?text=极KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "12 LPA",
    "experience": "Honed coding expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "AJAY H Hegde",
    "role": "Designation",
    "location": "Chennai",
    "rating": 4.5,
    "pre": "Fresher",
    "post": " ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "9 LPA",
    "experience": "Gained project skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Chiranjeevi B Shankara",
    "role": "Designation",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": " Accenture - ASE",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "15 LPA",
    "experience": "Built technical skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Harshitha K M",
    "role": "Designation",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capgemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "XYZ Institute",
    "degree": "B.Tech",
    "package": "11 LPA",
    "experience": "Learned software skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Kanneboyina Likith Adithya ",
    "role": "UI/UX DESIGNER",
    "location": "Bangalore",
    "rating": 5,
    "pre": "Fresher",
    "post": "EXL",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Lovely professional University ",
    "degree": "B.Tech",
    "package": "16 LPA",
    "experience": "Developed UI/UX design skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Gande Tejaswini  ",
    "role": "SDA",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": "Mortgage Loans",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Vaagdevi college of engineering  ",
    "degree": "B.Tech",
    "package": "13 LPA",
    "experience极": "Gained software development expertise in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "Suba Dharshini P",
    "role": "SDA",
    "location": "Pune",
    "rating": 3,
    "pre": "Fresher",
    "post": "Mortgage Loans",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Mahendra engineering college   ",
    "degree": "MCA",
    "package": "10 LPA",
    "experience": "Enhanced coding proficiency through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/suba-dharshini-p-51325323a"
  },
  {
    "name": "GILAKA SIVA PEDDANNA ",
    "role": "Management Trainee",
    "location": "Kolkata",
    "rating": 3,
    "pre": "Fresher",
    "post": "Saffron Sweets",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "KL UNIVERSITY ",
    "degree": "MBA",
    "package": "8 LPA",
    "experience": "Acquired management skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": ""
  },
  {
    "name": "K.J.Pavani Durga",
    "role": "Business Developement Associate",
    "location": "Chennai",
    "rating": 3,
    "pre": "Fresher",
    "post": "Rocklight",
    "image": "https://via.placeholder.com/80?text=极KC",
    "college": "Sri Padmavati Mahila Viswa Vidyalayam ",
    "degree": "M.Com",
    "package": "15 LPA",
    "experience": "Honed business development skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "www.linkedin.com/in/pavani-durga-165408215"
  },
  {
    "name": "ANUSHA R",
    "role": "BACKEND SUPPORT",
    "location": "Delhi",
    "rating": 4,
    "pre": "Fresher",
    "post": "Phoenix business Advisory",
    "image": "https://via.placeholder.com/80?极text=KC",
    "college": "SRM INSTITUTE OF SCIENCE AND TECHNOLOGY  ",
    "degree": "Master of public health ",
    "package": "11 LPA",
    "experience": "Strengthened backend support skills during internship",
    "preRole": "Internship from Krutan极ic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/anu-sha-7b6a31233"
  },
  {
    "name": "Saanchitha D",
    "role": "AM - FP&A ",
    "location": "Mumbai",
    "rating": 4,
    "pre": "Fresher",
    "post": "Genpact",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Dayananda Sagar University",
    "degree": "Computer Science and Engineering ",
    "package": "9 LPA",
    "experience": "Improved budgeting and forecasting skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/saanchitha-devraj-21615022a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BtMaKdf50Tte4J%2B3zRFtpDQ%3D%3D"
  },
  {
    "name": "Gokulakannan K ",
    "role": "Process Associate",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "Hrim Innovation",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Kalasalingam Academy of Research and Education ",
    "degree": "B.Tech CSE",
    "package": "16 LPA",
    "experience": "Gained process optimization skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "极https://www.linkedin.com/in/gokulakannan-k-51277b242"
  },
  {
    "name": "Anusha G",
    "role": "Sr Executive- Accounts",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Genpact",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Annamacharya institute of technology and science ",
    "degree": "ECE",
    "package": "13 LPA",
    "experience": "Enhanced accounting skills through internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/anusha-g-93968834a?"
  },
  {
    "name": "Rishabh Nagar",
    "role": "Process Associate ",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Brillo",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "极Chandigarh University  ",
    "极degree": "Be- cse",
    "package": "10 LPA",
    "experience": "Developed process management skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/rishabh-nagar-2895471a5"
  },
  {
    "name": "Jayita Ghorai ",
    "role": "Full stack developer",
    "location": "Delhi",
    "rating": 5,
    "pre": "Fresher",
    "post": "Capegemini",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "College of Engineering and Management, Kolaghat ",
    "degree": "Bachelor of Technology ",
    "package": "17 LPA",
    "experience": "Mastered full stack development during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/jayita-ghorai-867a4b261?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
  },
  {
    "name": "Bhavin Sali ",
    "role": "AM - FP&A ",
    "location": "Bangalore",
    "rating": 4,
    "pre": "Fresher",
    "post": "ValTech India",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "SRM University",
    "degree": " MCA ",
    "package": "12 LPA",
    "experience": "Built financial planning skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/bhavin-s307/"
  },
  {
    "name": "HRUSHIKESH S ",
    "role": "Ui/UX DESIGNER",
    "location": "Mumbai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Eco Lbs ",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "SJCIT ",
    "degree": "极CSE",
    "package": "9 LPA",
    "experience": "Refined user interface design skills during internship",
    "preRole": "Internship from Krutanic",
    "post极Role": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/hrushikesh-s-520a8b27a?utm_source=极share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
  },
  {
    "name": "Kartik chauhan ",
    "role": "Technical bug checker",
    "location": "Pune",
    "rating": 4,
    "pre": "Fresher",
    "post": "6d technologies",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "JC Bose University of science and technology ",
    "degree": "B.tech(computer engineering)",
    "package": "15 LPA",
    "experience": "Sharpened debugging skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "www.linkedin.com/in/kartik-chauhan-4b0041230"
  },
  {
    "name": "K J Pavani Durga ",
    "极role": "Management Trainee",
    "location": "Kolkata",
    "rating": 4,
    "pre": "Fresher",
    "post": "Brillo",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Sri Padmavati Mahila Viswa Vidhayalayam ",
    "degree": "Finance ",
    "package": "11 LPA",
    "experience": "Cultivated leadership skills during internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/pavani-durga-165408215"
  },
  {
    "name": "Pushpanjali verma",
    "role": "Ui/UX DESIGNER",
    "location": "Chennai",
    "rating": 5,
    "pre": "Fresher",
    "post": "Accenture ASW",
    "image": "https://via.placeholder.com/80?text=KC",
    "college": "Kalinga institute of industrial technology ",
    "degree": "B.极tech",
    "package": "16 LPA",
    "experience": "Advanced user experience design skills in internship",
    "preRole": "Internship from Krutanic",
    "postRole": "Designation ",
    "linkdinUrl": "https://www.linkedin.com/in/pushpanjali-verma-3b757a2bb?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app"
  }
];

export default AlumniData;